### PR TITLE
Attempt to set connection state correctly

### PR DESCRIPTION
**Pull request by zkxs**
Not sure if this will work, as I usually don't end up needing the relay. Please test it!

### CODE REVIEW

**Comment by kazu0617** [comment]
i tried this one, but it seems this error(i don't use relay usually too, so use -forcerelay).
[ERROR][NeosModLoader/NeosLNLRelayDisabler] Could not invoke FailReason or ConnectionFailed setters!

**Comment by zkxs** [comment]
Ah, I think I see what was wrong. ConnectionFailed isn't a method, it's an event. I don't want to deal with that, so I'm taking a completely different approach now.

**Comment by zkxs** [comment]
Thanks for telling me about `-forcerelay`, I've tested and it looks like it's working as intended, and it falls back to steam sockets (if available)
```log
6:25:06 AM.232 (165 FPS)	SessionInfo. Id: S-7b77dc21-a797-412c-ab9f-27848fa210cc, Name: /var/temp, URLs: lnl-nat:///S-7b77dc21-a797-412c-ab9f-27848fa210cc, neos-steam://76561199056537298/4/S-7b77dc21-a797-412c-ab9f-27848fa210cc
6:25:07 AM.135 (165 FPS)	Resolving SessionID: 
6:25:07 AM.137 (165 FPS)	Joining session: lnl-nat:///S-7b77dc21-a797-412c-ab9f-27848fa210cc,neos-steam://76561199056537298/4/S-7b77dc21-a797-412c-ab9f-27848fa210cc
6:25:07 AM.138 (165 FPS)	NetworkInitStart
6:25:07 AM.139 (165 FPS)	Network manager: NetX.LNL_Manager - priority: 0
6:25:07 AM.139 (165 FPS)	Network manager: FrooxEngine.SteamNetworkManager - priority: -100
6:25:07 AM.142 (165 FPS)	Connecting to: lnl-nat:///S-7b77dc21-a797-412c-ab9f-27848fa210cc
6:25:07 AM.143 (165 FPS)	NAT Punchthrough failed, Connecting to Relay
6:25:07 AM.144 (165 FPS)	[DEBUG][NeosModLoader/NeosLNLRelayDisabler] Nulled RELAY_EP
6:25:13 AM.091 (165 FPS)	Disconnected: 52.165.32.220:12601, reason: ConnectionFailed, socketErrorCode: Success
6:25:13 AM.091 (165 FPS)	Connection failed: ConnectionFailed
6:25:13 AM.092 (165 FPS)	Creating connection for remoteId: 76561199056537298, channel: 4, sessionId: S-7b77dc21-a797-412c-ab9f-27848fa210cc
6:25:13 AM.092 (165 FPS)	Connecting to: neos-steam://76561199056537298/4/S-7b77dc21-a797-412c-ab9f-27848fa210cc
6:25:13 AM.102 (165 FPS)	Connection Status: k_ESteamNetworkingConnectionState_Connecting, State: Connecting, Connection: 51181256, Remote Identity: 76561199056537298
6:25:13 AM.102 (165 FPS)	Connection Status: k_ESteamNetworkingConnectionState_Connecting, State: Connecting, Connection: 3605314009, Remote Identity: 76561199056537298
6:25:13 AM.655 (165 FPS)	Connection Status: k_ESteamNetworkingConnectionState_FindingRoute, State: Connecting, Connection: 51181256, Remote Identity: 76561199056537298
6:25:13 AM.655 (165 FPS)	Connection Status: k_ESteamNetworkingConnectionState_FindingRoute, State: Connecting, Connection: 3605314009, Remote Identity: 76561199056537298
6:25:14 AM.008 (165 FPS)	Connection Status: k_ESteamNetworkingConnectionState_Connected, State: Connecting, Connection: 3605314009, Remote Identity: 76561199056537298
6:25:14 AM.008 (165 FPS)	Connection Status: k_ESteamNetworkingConnectionState_Connected, State: Connecting, Connection: 51181256, Remote Identity: 76561199056537298
6:25:14 AM.008 (165 FPS)	Connected to: neos-steam://76561199056537298/4/S-7b77dc21-a797-412c-ab9f-27848fa210cc
6:25:14 AM.014 (165 FPS)	Waiting for join grant
6:25:14 AM.657 (165 FPS)	Join Granted, Begin Data Model Init
6:25:15 AM.574 (165 FPS)	Starting running world: /var/temp
```

**Comment by kazu0617** [comment]
OK, thanks a lot of help me, and merged!

**Pull request merged**
